# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com
before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy
builds:

  - main: "./main.go"
    env:
      - CGO_ENABLED=0
   
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
      # - arm
      # - 386
    ldflags:
      ## auto inject commit and version at build time
      -  -X github.com/vdbulcke/goreleaser-hello-world/main.GitCommit={{ .ShortCommit }} 
      -  -X github.com/vdbulcke/goreleaser-hello-world/main.Version=v{{ .Version }}   
      -  -X github.com/vdbulcke/goreleaser-hello-world/main.Date={{ .CommitDate }}
      -  -X github.com/vdbulcke/goreleaser-hello-world/main.BuiltBy=goreleaser

archives:
  - 
    # replacements:
    #   darwin: Darwin
    #   linux: Linux
    #   windows: Windows
    #   386: i386
    #   amd64: x86_64
    name_template: >-
      {{ .ProjectName }}_{{ .Version }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    ## use zip for windows release
    format_overrides:
      - goos: windows
        format: zip
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

signs:
  - cmd: cosign
    signature: "${artifact}.sig"
    args: ["sign-blob", "--oidc-issuer=https://token.actions.githubusercontent.com", "--output-signature=${artifact}.sig", "${artifact}"]
    artifacts: all

dockers:
  - 
    id: linux-amd64
    # GOOS of the built binaries/packages that should be used.
    goos: linux

    # GOARCH of the built binaries/packages that should be used.
    goarch: amd64

    # GOARM of the built binaries/packages that should be used.
    goarm: ''

    dockerfile: Dockerfile

    ## Mutli platform 
    use: buildx
    build_flag_templates:
    - --platform=linux/amd64

    image_templates:
    - "ghcr.io/vdbulcke/goreleaser-hello-world:v{{ .Version }}"

  - 
    id: linux-arm64
    # GOOS of the built binaries/packages that should be used.
    goos: linux

    # GOARCH of the built binaries/packages that should be used.
    goarch: arm64

    # GOARM of the built binaries/packages that should be used.
    goarm: ''

    dockerfile: Dockerfile

    ## Mutli platform 
    use: buildx
    build_flag_templates:
    - --platform=linux/arm64/v8

    image_templates:
    - "ghcr.io/vdbulcke/goreleaser-hello-world-arm64:v{{ .Version }}"


release:


  # ## set github header and footer
  # header: |
  #   ## Docker

  #   repo: 
  #   ```bash
  #   docker pull vdbulcke/test:{{ .Tag }}
  #   ```

  # Footer template for the release body.
  # Defaults to empty.
  footer: |
    ## Thanks!

    Those were the changes on {{ .Tag }}!